-- GROUP BY + WHERE
SELECT*FROM DimProduct

SELECT
	COLORNAME AS COR,
	COUNT(*) AS CONTAGEM
FROM
DimProduct
WHERE BRANDNAME = 'CONTOSO'
GROUP BY ColorName

--GROUP BY + HAVING
SELECT 
	BRANDNAME AS MARCA,
	COUNT(BRANDNAME) AS 'TOTAL POR MARCA'
FROM DimProduct
GROUP BY BrandName
HAVING COUNT(BRANDNAME) > 200

