SELECT TOP(100) * FROM FactSales


SELECT SUM(SALESQUANTITY) AS TOTAL_VENDIDO,
	SUM(RETURNQUANTITY) AS QUANTIDADE_DEVOLVIDA
	FROM FactSales

SELECT COUNT(ProductName) AS 'TOTAL DE PRODUTOS'
FROM
DimProduct
WHERE Status IS NOT NULL

SELECT COUNT(DISTINCT COLORNAME)
FROM DimProduct

SELECT
	MAX(UNITPRICE) AS PREÇO_MÁXIMO,
	MIN(UNITPRICE) AS PREÇO_MÍNIMO
FROM DimProduct